version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - microservices-network
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    restart: unless-stopped

  brt_postgres:
    image: postgres:16-alpine
    container_name: brt_postgres_db
    volumes:
      - brt-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brtdb
    ports:
      - "5432:5432"
    networks:
      - microservices-network
    restart: unless-stopped

  hrs_postgres:
    image: postgres:16-alpine
    container_name: hrs_postgres_db
    volumes:
      - hrs-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hrsdb
    ports:
      - "5433:5432"
    networks:
      - microservices-network
    restart: unless-stopped

networks:
  microservices-network:
    driver: bridge

volumes:
  brt-postgres-data:
  hrs-postgres-data: