version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: hrs-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hrs-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
volumes:
  postgres_data: