CREATE TABLE IF NOT EXISTS users
(
    id         BIGINT PRIMARY KEY AUTO_INCREMENT,
    first_name VARCHAR(255) NOT NULL,
    name  VARCHAR(255) NOT NULL,
    number     VARCHAR(255) NOT NULL UNIQUE
)