version: '3.8'

services:
  h2-db:
    image: oscarfonts/h2
    container_name: h2-database
    environment:
      - H2_OPTIONS=-webAllowOthers -tcpAllowOthers -ifNotExists
    ports:
      - "8082:8082"  # Веб-консоль (http://localhost:8082)
      - "9092:9092"  # TCP-порт для JDBC подключения
    volumes:
      - h2-data:/opt/h2-data
    restart: unless-stopped

volumes:
  h2-data: