spring:
  application:
    name: cdr-service
  sql:
    init:
      mode: always
      schema-locations: classpath:db/sql/schema.sql
      data-locations:  classpath:db/sql/data.sql
  datasource:
    url: jdbc:h2:mem:testdb
    username: admin
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  profiles:
    active: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

cdr-reports:
  path: src/main/java/reports

