spring:
  application:
    name: cdr-service
  datasource:
    url: jdbc:h2:mem:testdb
    username: admin
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  profiles:
    active: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password

server:
  port: 8081

rabbitmq:
  exchange-name: cdr-exchange
  cdr-created-queue: cdr.queue
  cdr-created-routing-key: cdr

cdr:
  max-cdr-amount-before-sending-to-queue: 10
  amount-of-cdr-generations-at-one-time: 1000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

