server:
  port: 8083

spring:
  application:
    name: hrs-service
  datasource:
    url: jdbc:postgresql://localhost:5431/hrs-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
