spring:
  application:
    name: hrs-service
  datasource:
    url: jdbc:postgresql://localhost:5433/hrsdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  profiles:
    active: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password
  logging:
    level:
      org:
        hibernate:
            SQL: DEBUG
            type:
              descriptor:
                sql:
                  BasicBinder: TRACE
server:
  port: 8083