spring:
  application:
    name: eureka-server

server:
  port: 8761
  servlet:
    context-path: /

eureka:
  instance:
    hostname: eureka-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka