name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Start containers
        run: docker-compose up -d --build

      - name: Wait for containers to start
        run: sleep 10

      - name: Install test dependencies
        working-directory: ./autotests/
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run autotests
        run: python -m pytest

      - name: Stop containers
        run: docker-compose down

      - name: Show logs if tests fail
        if: failure()
        run: docker-compose logs