spring:
  application:
    name: brt-service
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: create-drop
  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: password


server:
  port: 8082


rabbitmq:
    exchange-name: brt-exchange
    call-created-queue: call.queue
    call-created-routing-key: call