spring:
  application:
    name: brt-service
  datasource:
    url: jdbc:postgresql://localhost:5432/brtdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password


server:
  port: 8082

rabbitmq:
  exchange-name: brt-exchange
  cdrs-created-queue: cdr.queue
  call-created-queue: call.queue
  bill-created-queue: bill.queue
  call-created-routing-key: call